"""Criando tabela GeneroLivro

Revision ID: 1757eb063711
Revises: e3552b3bf601
Create Date: 2025-04-12 20:51:26.273770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1757eb063711'
down_revision = 'e3552b3bf601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GeneroLivro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GeneroLivro')
    # ### end Alembic commands ###
