"""Criando tabela Carrinho

Revision ID: 1ab65f82c11e
Revises: 3383496ab1d3
Create Date: 2025-04-12 20:58:45.500967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab65f82c11e'
down_revision = '3383496ab1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], name='fk_carrinho_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Carrinho')
    # ### end Alembic commands ###
