"""Removendo o campo de formato e tipo da table de Livro

Revision ID: 1aff82ab3088
Revises: 902bf3088602
Create Date: 2025-06-28 09:33:48.961496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aff82ab3088'
down_revision = '902bf3088602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.drop_column('tipo')
        batch_op.drop_column('formato')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formato', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=40), nullable=False))

    # ### end Alembic commands ###
