"""Criando tabela de Carrinho

Revision ID: 345f136a35de
Revises: 03f368a77f41
Create Date: 2025-04-13 19:26:28.032829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345f136a35de'
down_revision = '03f368a77f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carrinho',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], name='fk_carrinho_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Carrinho')
    # ### end Alembic commands ###
