"""Adicionando uuid4 ao id do GeneroLivro

Revision ID: 48acdf394ff2
Revises: 9efe2a4ea8d5
Create Date: 2025-04-12 23:17:24.888307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48acdf394ff2'
down_revision = '9efe2a4ea8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GeneroLivro', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GeneroLivro', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
