"""Criando tabela Pagamento

Revision ID: 4b43f499e66c
Revises: bd596ab87e14
Create Date: 2025-04-12 21:06:14.870330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b43f499e66c'
down_revision = 'bd596ab87e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pagamento')
    # ### end Alembic commands ###
