"""Adicionando uuid4 ao id do pagamento

Revision ID: 541ab34eac8e
Revises: 1ce69d8c41ae
Create Date: 2025-04-12 23:13:03.930721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541ab34eac8e'
down_revision = '1ce69d8c41ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pagamento', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pagamento', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
