"""Criando Tabela de Estado

Revision ID: 5d6e8d5464d9
Revises: 6285f486abfe
Create Date: 2025-04-15 22:13:26.729972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6e8d5464d9'
down_revision = '6285f486abfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado')
    # ### end Alembic commands ###
