"""Adicionando uuid4 ao id do livro

Revision ID: 62168431af01
Revises: 541ab34eac8e
Create Date: 2025-04-12 23:14:27.547001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62168431af01'
down_revision = '541ab34eac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
