"""Criando tabela de Estado

Revision ID: 7aca112c3b12
Revises: 9d94cf2d4c16
Create Date: 2025-04-13 19:15:01.741129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aca112c3b12'
down_revision = '9d94cf2d4c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Estado',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Estado')
    # ### end Alembic commands ###
