"""Criando tabela Pedido

Revision ID: 7fbbf0ed6cc4
Revises: 4b43f499e66c
Create Date: 2025-04-12 21:07:49.709713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbbf0ed6cc4'
down_revision = '4b43f499e66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('id_pagamento', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('taxa_frete', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_endereco'], ['Endereco.id'], name='fk_pedido_endereco', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pagamento'], ['Pagamento.id'], name='fk_pedido_pagamento', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], name='fk_pedido_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pedido')
    # ### end Alembic commands ###
