"""Adicionando o campo de formato e tipo da table de Item-Pedido

Revision ID: 89f12d3479e3
Revises: 1aff82ab3088
Create Date: 2025-06-28 09:46:42.671758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f12d3479e3'
down_revision = '1aff82ab3088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemPedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formato', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemPedido', schema=None) as batch_op:
        batch_op.drop_column('tipo')
        batch_op.drop_column('formato')

    # ### end Alembic commands ###
