"""Adicionando campos na table ItemCarrinho

Revision ID: 902bf3088602
Revises: c4dd8eddac6d
Create Date: 2025-06-22 19:39:22.905209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902bf3088602'
down_revision = 'c4dd8eddac6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemCarrinho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('preco_unitario', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemCarrinho', schema=None) as batch_op:
        batch_op.drop_column('preco_unitario')
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###
