"""Criando tabela de Pagamento

Revision ID: 95a2103c60bd
Revises: 3caacd62ae3c
Create Date: 2025-04-13 19:30:32.154596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a2103c60bd'
down_revision = '3caacd62ae3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pagamento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pagamento')
    # ### end Alembic commands ###
