"""Criando tabela de Endereco

Revision ID: a8319f9611fc
Revises: 7aca112c3b12
Create Date: 2025-04-13 19:17:24.150286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8319f9611fc'
down_revision = '7aca112c3b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Endereco',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=40), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['Estado.id'], name='fk_endereco_estado', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], name='fk_endereco_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Endereco')
    # ### end Alembic commands ###
