"""Criando tabela de Autor

Revision ID: ae980af895f9
Revises: a8319f9611fc
Create Date: 2025-04-13 19:19:53.061344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae980af895f9'
down_revision = 'a8319f9611fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Autor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Autor')
    # ### end Alembic commands ###
