"""Criando tabela ItemCarrinho

Revision ID: bd596ab87e14
Revises: 1ab65f82c11e
Create Date: 2025-04-12 21:01:30.674007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd596ab87e14'
down_revision = '1ab65f82c11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemCarrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrinho', sa.Integer(), nullable=False),
    sa.Column('id_livro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrinho'], ['Carrinho.id'], name='fk_itemcarrinho_carrinho', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_livro'], ['Livro.id'], name='fk_itemcarrinho_livro', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemCarrinho')
    # ### end Alembic commands ###
