"""Criando tabela de Assinatura

Revision ID: c1ff86f94903
Revises: 1135f716eb1d
Create Date: 2025-04-13 19:35:10.083108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ff86f94903'
down_revision = '1135f716eb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Assinatura',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_assinatura', sa.String(length=40), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('preco_assinatura', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], name='fk_assinatura_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Assinatura')
    # ### end Alembic commands ###
