"""Criando tabela ItemPedido

Revision ID: c6486b53534c
Revises: 7fbbf0ed6cc4
Create Date: 2025-04-12 21:10:08.875121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6486b53534c'
down_revision = '7fbbf0ed6cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemPedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_livro', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_livro'], ['Livro.id'], name='fk_itempedido_livro', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['Pedido.id'], name='fk_itempedido_pedido', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemPedido')
    # ### end Alembic commands ###
