"""Criando tabela Autor

Revision ID: e3552b3bf601
Revises: ef90781c235f
Create Date: 2025-04-12 20:46:14.099981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3552b3bf601'
down_revision = 'ef90781c235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Autor')
    # ### end Alembic commands ###
